replicaCount: 1

image:
  repository: prom/prometheus
  pullPolicy: IfNotPresent
  tag: "v2.47.0"

service:
  type: NodePort
  port: 9090
  nodePort: 30090

resources:
  limits:
    cpu: 300m
    memory: 385Mi
  requests:
    cpu: 50m
    memory: 128Mi

persistence:
  enabled: true
  size: 2Gi
  